# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BhamGemz' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BhamGemz

  # target 'BhamGemz-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  target 'BhamGemzTests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'GoogleMaps'

end

# target 'BhamGemz-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for BhamGemz-tvOS

#   target 'BhamGemz-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end
